services:
  - type: web
    name: shopping-hair-skin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard_competidores.py --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8501 